### ISSUE TITLE
Support mongo-java-driver 3.0.0 in mongojack

### ISSUE THREAD

**Issue by kfowler** [devbliss/mongojack#103]
Support mongo-java-driver 3.0.0. Allow for using 2.13 or later or 3.0 driver in "provided" scope.

https://github.com/mongodb/mongo-java-driver/releases/tag/r3.0.0

**Comment by benmccann** [comment]
This seems to be fixed by https://github.com/devbliss/mongojack/commit/0bfe5e34d33db305d75c0a2d4eb4e326476fc924
