### ISSUE TITLE
Tests do not pass on MongoDB 2.6

### ISSUE THREAD

**Issue by benmccann** [devbliss/mongojack#71]
To reproduce, change the version of MongoDB that the tests are run with. Currently hardcoded to Version.Main.V2_4 in src/test/java/org/mongojack/testing/DbManager.java

If I comment out the following code in JacksonDBObject then the tests begin to pass:

        if ("_id".equals(key)) {
            return "Generated _id retrieval not supported when using stream serialization";
        }

**Comment by laGenteEstaMuyLoca81** [comment]
@benmccann Thanks for reporting the issue. We analyzed the mysterious if-block mentioned above and came to the conclusion that it can be removed without any worries. So we did :)
Just released version 2.2 to maven central.

**Comment by benmccann** [comment]
awesome!
