### ISSUE TITLE
Release 2.3.0

### ISSUE THREAD

**Issue by benmccann** [devbliss/mongojack#90]
@marcelb @roughy thanks for cutting the release. would it be possible to do another?

we added MongoDB 3.0 compatibility just after the release was cut. i'd love to get the 3.0 compatible version out since MongoDB 3.0 will be released very soon. sorry about the miscommunication. thought you guys knew about the pending PR

https://github.com/devbliss/mongojack/commit/cdb4d61648fc2cfeae8df558fafc8cca2c3dd65e
https://github.com/devbliss/mongojack/commit/774780cd4bc4cb8ec8f3e1e6e27dff7daec32257

**Comment by benmccann** [comment]
MongoDB 3.0 was announced today (https://www.mongodb.com/blog/post/announcing-mongodb-30). I'd love to get a new release out before then if possible. We can migrate the project from devbliss to connectifier after that if you guys wish

**Comment by marcelb** [comment]
Hi @benmccann !

Sorry, for replying late! Yeah, we can do this! I can release the current master today or is a PR missing?

Cheers!
Marcel

**Comment by benmccann** [comment]
That'd be great! Thanks! No PR missing.

**Comment by marcelb** [comment]
In case you didn't notice: It got released on Friday :)

http://search.maven.org/#artifactdetails%7Corg.mongojack%7Cmongojack%7C2.3.0%7Cbundle

**Comment by benmccann** [comment]
That's great! Thanks so much!
