### ISSUE TITLE
MongoJack.org site disabled

### ISSUE THREAD

**Issue by StevenACoffman** [devbliss/mongojack#92]
When I view the MongoJack.org website, I get a "Site Disabled" message:
> Site Disabled
> 
> Oh no! It looks like this Pages site has been disabled due to a misconfigured custom domain.
> 
> Are you the site owner? You can quickly fix this issue by updating the DNS record for your Pages site:
> 
> If you're using a subdomain (coolthing.example.com, www.example.com, etc.), make sure you have a CNAME record that points to your-username.github.io.
> If you're not using a subdomain (example.com), make sure you have two A records set to the following IPs: 192.30.252.153 and 192.30.252.154

**Comment by benmccann** [comment]
Looks like it's working for me. Maybe it was some temporary problem earlier
