### ISSUE TITLE
Bug in DBCursor.putGroup()

### ISSUE THREAD

**Issue by kdkeck** [devbliss/mongojack#94]
Calling `DBCursor.and(Query...)` fails to modify the query, in some cases. I've created a PR showing the problem: #93

Without the Ignore tag, it produces the following error:
```
  TestDBCursor.testPutGroup:81 
Expected: not "{ \"$and\" : [ { \"string\" : { \"$exists\" : true}}]}"
     but: was "{ \"$and\" : [ { \"string\" : { \"$exists\" : true}}]}"
```

**Comment by benmccann** [comment]
Fixed by https://github.com/devbliss/mongojack/pull/95
